pipeline {
    agent any
    
    stages {
        stage('Clonar Repositorio') {
            steps {
                git 'https://github.com/Arleyd2001/TiendaMascotasQr.git'
            }
        }
        
        stage('Instalar Dependencias') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Ejecutar Pruebas') {
            steps {
                sh 'npm test'
            }
            
            post {
                always {
                    junit 'reports/**/*.xml'
                }
            }
        }
    }
    
    post {
        success {
            echo 'Pruebas completadas satisfactoriamente!'
        }
        failure {
            echo 'Pruebas fallaron. Revisar logs para más detalles.'
        }
    }
}
